/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
/** New line translator. */
package com.bs.core.parser;

public interface ExpressionParserConstants {

  int EOF = 0;
  int IF = 5;
  int ELSEIF = 6;
  int ELSE = 7;
  int ABS = 8;
  int SIN = 9;
  int COS = 10;
  int LOG = 11;
  int LOG10 = 12;
  int SQRT = 13;
  int TAN = 14;
  int BIGGERTHEN = 15;
  int SMALLERTHEN = 16;
  int NOTSMALLERTHEN = 17;
  int NOTBIGGERTHEN = 18;
  int EQUALS = 19;
  int NOTEQUALS = 20;
  int AND = 21;
  int OR = 22;
  int NOT = 23;
  int PLUS = 24;
  int MINUS = 25;
  int TIMES = 26;
  int DIVIDE = 27;
  int STRING = 28;
  int NUMBER = 29;
  int DIGITS = 30;
  int LETTER = 31;
  int OPEN_PAR = 32;
  int CLOSE_PAR = 33;
  int OPEN_BRACE = 34;
  int CLOSE_BRACE = 35;
  int SEMICOLON = 36;
  int DOUBLE_QUOTE = 37;
  int SINGLE_QUOTE = 38;
  int NULL = 39;
  int TRUE = 40;
  int FALSE = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"abs\"",
    "\"sin\"",
    "\"cos\"",
    "\"log\"",
    "\"log10\"",
    "\"sqrt\"",
    "\"tan\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<STRING>",
    "<NUMBER>",
    "<DIGITS>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
  };

}
